package com.zhdanon.skillcinema.core

enum class CategoriesMovies {
    TOP_250_MOVIES,
    TOP_POPULAR_MOVIES,
    PREMIERES,
    TOP_POPULAR_ALL,
    TOP_250_TV_SHOWS,
    VAMPIRE_THEME,
    COMICS_THEME,
    CLOSES_RELEASES,
    FAMILY,
    OSKAR_WINNERS_2021,
    LOVE_THEME,
    ZOMBIE_THEME,
    CATASTROPHE_THEME,
    KIDS_ANIMATION_THEME,
    TV_SERIES
}